dnanexus/dxCompiler

.github/workflows/integration.yml
.github/workflows/scala.yml
scripts/run_tests.py
scripts/util.py

This commit will make it easier to run integration tests for the WDL compiler. 
The changes include:
- fix unit tests which don't kick off - change master to main in the existing workflow
- add `--clean` option to the `run_tests.py` script that removes the build folder after running tests
- integration tests will run when the `integration` label is set on a PR. This is to limit running them to devs with write access to the repo (write access is needed to set labels) and also limit the number of runs so that we don't incur too much cost. 
- the test script will now fail with a non-zero exit code if any of the workflows fail.

APPS-249 Run integration tests from GHA

---

src/main/scala/dx/core/languages/wdl/WdlBlock.scala
src/main/scala/dx/core/languages/wdl/WdlUtils.scala
src/main/scala/dx/executor/wdl/WdlWorkflowSupport.scala
src/main/scala/dx/translator/wdl/CallableTranslator.scala
src/test/resources/util/nested_closure.wdl
src/test/resources/util/nested_closure_no_fw_ref.wdl
src/test/scala/dx/core/languages/wdl/WdlBlockTest.scala
src/test/scala/dx/core/languages/wdl/WdlUtilsTest.scala

Refactor getClosureInputsAndOutputs to correctly handle out-of-order statements (i.e. forward references). This is a continuation of APPS-247 - I can either merge this with the bugs/APPS-247 first, or wait until that one is merged and then change this PR to be against main.
This highlights the issue that forward references are currently not handled during type inference. I have added an issue (APPS-273) to address this later.

refactor getClosureInputsAndOutputs to respect dependency order

---

build.sbt

This fixes two bugs uncovered in RC5
- struct literals rendered incorrectly for v1
- array type-checking is too strict (can't coerce between empty and non-empty array types)

upgrade to wdlTools 0.10.7

---

.github/workflows/scala.yml
compiler/src/test/scala/dx/compiler/CompilerTest.scala
compiler/src/test/scala/dx/dxni/DxNativeInterfaceTest.scala

Problem with paralel tests was probably caused due to two sets of tests creating/deleting applets folder which tests use. Currently no applets are removed and folders are named using timestamp and UUID (timestamp for easier debugging when browsing filesystem and UUID is used in case two tests were started at the same time)
Applets-folder-deletion mechanism is changed from "Deleted when starting" to "deleted after tests are finished. Is this fine?

APPS-291 unit-tests GHA fix

---

compiler/src/test/scala/dx/compiler/CompilerTest.scala
compiler/src/test/scala/dx/dxni/DxNativeInterfaceTest.scala
doc/ExpertOptions.md

APPS-329 Update file URL, use generic IDs in documentation. 
The other changes were done by the scalafmt commit hook.

APPS-329 Update file URL, use generic IDs in documentation. 

---

RELEASE_NOTES.md
scripts/bundled_dependencies.json

Note: dxfuse 0.23.3 is mounted in readOnly mode by default

APPS-235 Upgrade dxfuse to 0.23.3

---

RELEASE_NOTES.md
build.sbt
compiler/src/main/scala/dx/dxni/wdl/WdlNativeInterfaceGenerator.scala
compiler/src/main/scala/dxCompiler/Main.scala
compiler/src/test/scala/dx/dxni/DxNativeInterfaceTest.scala

Currently, dxni skips any app(let)s with unsupported parameter types, but in the case of optional unsupported types, we can just ignore them.
This also updates to dxApi 0.1.9 to fix a bug with app (and globalworkflow) object ID parsing.

APPS-389: handle optional non-file object inputs in native app(let)s

---

compiler/src/main/scala/dx/compiler/ApplicationCompiler.scala
core/src/main/scala/dx/core/ir/ValueSerde.scala
core/src/main/scala/dx/core/languages/wdl/CodeGenerator.scala
executorWdl/src/main/scala/dx/executor/wdl/WdlWorkflowExecutor.scala

Don't use instance type from wrapper task on native task.
When generating task stub, include meta section with type=native for native task.

APPS-344 Native tasks should use instance type from native app/let, not wrapper task.

---

.github/workflows/release.yml
scripts/build_release.py

This is to fix:
```
building staging release
File "/home/runner/work/dxCompiler/dxCompiler/scripts/build_release.py", line 54
file=sys.stderr)
^
SyntaxError: invalid syntax
Error: Process completed with exit code 1.
```

APPS-324 Set build script to run on python3; fix test step

---

RELEASE_NOTES.md
compiler/src/main/scala/dx/translator/wdl/CallableTranslator.scala
compiler/src/test/resources/bugs/native_with_file_output.wdl
compiler/src/test/resources/bugs/subwf.wdl
compiler/src/test/scala/dx/compiler/CompilerTest.scala

WDL requires that all output declarations have a value assigned, but in effect these values are ignored for native apps. This PR changes the WDL translator to not eval add default values to the IR `Parameter` instances for native app stub output parameters, because these can cause issues when they are copied.

Ignore default values in native app stubs

---

.github/workflows/release.yml
doc/Developing.md

* Builds a release directly from main, doesn't push any branch back
* Runs large integration tests by default
* Adds input validation
* Removes release entry rollback (so that the drafted page is kept in case of failure)

APPS-324 Simplify release pipeline; add docs

---

RELEASE_NOTES.md
compiler/src/main/scala/dx/translator/wdl/CallableTranslator.scala

Using the wrong name causes applet name collisions, which causes compilation to fail for complex nested workflows.

use wfName instead of wf.name in call to createCommonApplet

---

executorWdl/src/main/scala/dx/executor/wdl/WdlWorkflowExecutor.scala
executorWdl/src/test/resources/bugs/opt_with_default.wdl
executorWdl/src/test/scala/dx/executor/wdl/WorkflowExecutorTest.scala

Currently a workflow like the following fails with an error. This PR fixes the handling of null values specified for optional call parameters.
```wdl
version 1.1
workflow Test {
input {
Int? opt
}
call Foo {
input: opt=opt
}
}
task Foo {
input {
Int? opt = 20
}
command <<<
echo ~{default="20" opt}
>>>
}
```

APPS-419 handle optional call parameters with null arguments

---

core/src/main/scala/dx/core/languages/wdl/WdlUtils.scala
core/src/test/resources/bugs/apps-422.wdl
core/src/test/scala/dx/core/languages/wdl/WdlBlockTest.scala
executorWdl/src/test/resources/bugs/apps-422.wdl
executorWdl/src/test/scala/dx/executor/wdl/WorkflowExecutorTest.scala

If a `WdlBlock` contains a declaration of an object or struct type, it will yield a `WdlBlockInput` with a compound name. For example:
```wdl
Struct Foo {
String s
}
workflow bar {
Foo f = object { s: "hello" }
String s = f.s
}
```
yields a `RequiredBlockInput("f.s")`
However, when this is evaluated, the environment only contains `f` so it results in a missing required input. This PR fixes this scenario by searching for the fully qualified name and all possible sub-names in the environment.

APPS-422 - handle block inputs that are compound reference to private variables

---

RELEASE_NOTES.md
build.sbt
compiler/src/main/resources/templates/applet_script.ssp
core/src/main/scala/dx/core/io/DxfuseManifest.scala
executorCommon/src/main/scala/dx/executor/TaskExecutor.scala
scripts/run_tests.py
test/bugs/diff_stream_and_download.wdl
test/bugs/diff_stream_and_download_input.json

The issue was in the generated job script in the bash code block for dxda - it cd's to / at the beginning and then is supposed to cd back to the home directory at the end, but instead it was cd-ing to the work dir. This only causes an issue if dxfuse is also used, because it tries to source environment, which is in the home dir. The error was not showing up in the log because we pipe the output from `source environment` to /dev/null to avoid leaking the token to the logs, so it was also swallowing the error message.
Also fixes the parent directory name written to the dxfuse manifest (removes the extra leading '/').
Also updates to dxCommon 0.2.10 which fixes another issue - the LocalizationDisambiguator was creating directories in the dxfuse mount point, which is wrong behavior, but I …

APPS-288 - fixes issue with using both streaming and non-streaming files

---

RELEASE_NOTES.md
compiler/src/main/resources/templates/ecr_docker_preamble.ssp
compiler/src/main/scala/dx/translator/wdl/CallableTranslator.scala
compiler/src/test/resources/bugs/scatter_inside_if.wdl
compiler/src/test/scala/dx/translator/TranslatorTest.scala
executorWdl/src/test/scala/dx/executor/wdl/TaskExecutorTest.scala

Computed inputs (i.e. scatter variables) need to be excluded from workflow inputs.

APPS-456 fixes issue with having a scatter as the first workflow element

---

compiler/src/main/resources/templates/ecr_docker_preamble.ssp
compiler/src/main/resources/templates/generic_docker_preamble.ssp

this change avoids echoing docker passwords to the job log

don't log docker passwords

---

compiler/src/main/resources/templates/applet_script.ssp
compiler/src/main/resources/templates/ecr_docker_preamble.ssp
compiler/src/main/resources/templates/generic_docker_preamble.ssp
doc/ExpertOptions.md
executorCommon/src/main/scala/dx/executor/JobMeta.scala
executorWdl/src/main/scala/dx/executor/wdl/WdlWorkflowExecutor.scala
scripts/run_tests.py
test/manifest/view_and_count_manifest.wdl
test/manifest/view_and_count_manifest_input.json

The output manifest keys may be prefixed with the execution name, so if the short name is not present we need to try with the long name.

APPS-462 fix issue with scatter collect when using manifests

---

compiler/src/main/resources/templates/ecr_docker_preamble.ssp
compiler/src/main/resources/templates/generic_docker_preamble.ssp
scripts/bundled_dependencies.json
scripts/util.py

There are still intermittent issues with installing the AWS CLI at runtime. This PR packages the AWS CLI installer with the executor. Also fixes echoing of passwords to the log (for real this time).

use static AWS client, don't echo password

---

build.sbt
doc/CustomReorgAppletExample.md
doc/ExpertOptions.md
executorCommon/src/main/scala/dx/executor/WorkflowExecutor.scala

The analysis is updated in the backend asynchronously, so we need to check the `dependsOn` field to determine if it is still waiting on the output of a previous stage before we can proceed with the reorg.
This PR also updates to the latest dxScala dependencies.

APPS-534 poll analysis on reorg

---

RELEASE_NOTES.md
compiler/src/main/scala/dx/translator/wdl/CallableTranslator.scala
compiler/src/test/resources/nested/nested_scatter.wdl
compiler/src/test/scala/dx/translator/TranslatorTest.scala
core/src/main/scala/dx/core/languages/wdl/WdlBlock.scala
test/nested/nested_scatter.wdl
test/nested/nested_scatter_results.json

The problem is illustrated by this WDL snippet:
```
Array[Int] ints1 = [1, 2, 3]
Array[Int] ints2 = [10, 11]
scatter (x in ints1) {
scatter (y in ints2) {
call xxx_add{ input: a = x, b = y }
Int i = ints1[x-1]
if (i < 3) {
String s = "hello ${x} ${y}"
}
}
}
```
Currently, `ints1` and `ints2` are not added to the environment when translating the inner scatter, so the generated applet is missing inputs for those. This PR fixes the issue.

APPS-512 - add private variables from outer scope to env when computing inputs of nested scatters

---

scripts/run_tests.py

Fixing some issues in our integration test script:
* `verify_test` only failed if the last expected output to be checked is invalid
* Result failed validation if it was missing even if the expected value was `None` (i.e. the field is optional)
* Result failed validation if there was a mismatch between list values where the expected result contains `None` - DNAnexus does not preserve `null`s in outputs.

Fix integration test bugs

---

RELEASE_NOTES.md
compiler/src/main/scala/dx/compiler/Compiler.scala
compiler/src/main/scala/dx/compiler/DxExecutableDirectory.scala
compiler/src/test/resources/bugs/apps-788.wdl
compiler/src/test/scala/dx/compiler/CompilerTest.scala

Also improves `CompilerTest` to clean use a separate folder and clean it up at the end of the suite.

APPS-788 fix project-wide reuse
